// R Aura v2.1 — pure renderer. R owns the state; UI never infers emotion from text.
(function(){
  const V='2.1.0';
  const K={aura:'red.a8.server.auraState',peak:'red.a8.server.peakEvent',peakSeen:'red.a8.aura.peakSeen'};
  const particles=new Set(['none','bubbles','sparks','mist','rain','embers','hearts','stars']);
  const motions=new Set(['still','slow','float','pulse','drift']);
  let current=null,ambientKey='';
  const safe=(s,f=null)=>{try{return JSON.parse(s)}catch{return f}};
  const bound=(v,a,b,f)=>{const n=Number(v);return Number.isFinite(n)?Math.max(a,Math.min(b,n)):f};
  const legacyMap={calm:{name:'平静',hue:346,secondaryHue:326,saturation:47,lightness:53,intensity:24,particle:'none',motion:'slow'},happy:{name:'开心',hue:31,secondaryHue:8,saturation:72,lightness:62,intensity:54,particle:'sparks',motion:'float'},teasing:{name:'暧昧',hue:334,secondaryHue:286,saturation:76,lightness:64,intensity:70,particle:'bubbles',motion:'float'},sad:{name:'低落',hue:221,secondaryHue:267,saturation:34,lightness:57,intensity:38,particle:'rain',motion:'slow'},hesitant:{name:'犹豫',hue:318,secondaryHue:234,saturation:42,lightness:65,intensity:42,particle:'mist',motion:'drift'}};
  function legacy(a){return {...(legacyMap[String(a?.mode||'calm')]||legacyMap.calm),updatedAt:Number(a?.updatedAt||0)}}
  function norm(a){
    if(!a||typeof a!=='object')return null;if(a.mode&&!Number.isFinite(Number(a.hue)))a=legacy(a);const d=legacy({mode:'calm'});
    return {name:String(a.name||d.name).slice(0,32),hue:Math.round(bound(a.hue,0,359,d.hue)),secondaryHue:Math.round(bound(a.secondaryHue??a.secondary_hue,0,359,d.secondaryHue)),saturation:Math.round(bound(a.saturation,18,96,d.saturation)),lightness:Math.round(bound(a.lightness,28,76,d.lightness)),intensity:Math.round(bound(a.intensity,0,100,d.intensity)),particle:particles.has(String(a.particle))?String(a.particle):d.particle,motion:motions.has(String(a.motion))?String(a.motion):d.motion,updatedAt:Number(a.updatedAt||0)};
  }
  function hsl(h,s,l,a=1){return `hsla(${h},${s}%,${l}%,${a})`}
  function installCSS(){
    if(document.getElementById('rAuraStyle'))return;const s=document.createElement('style');s.id='rAuraStyle';s.textContent=`
:root{--ra-accent:#cf4962;--ra-soft:rgba(153,47,72,.10);--ra-soft2:rgba(86,43,62,.07);--ra-border:rgba(187,65,91,.25);--ra-shadow:rgba(180,65,100,.06);--ra-user1:#5f1e2c;--ra-user2:#39151e;--ra-send2:#7e1f33;--ra-wash1:rgba(120,30,60,.04);--ra-wash2:rgba(80,35,70,.03);--ra-particle:rgba(255,170,210,.55);--ra-particle2:rgba(200,130,240,.32);--ra-fx-opacity:.35}
html,body{transition:background 1.05s ease,background-color 1.05s ease}body{background:radial-gradient(circle at 48% 2%,var(--ra-soft),transparent 40%),radial-gradient(circle at 86% 70%,var(--ra-soft2),transparent 44%),#09080a!important}body::before{content:"";position:fixed;inset:0;pointer-events:none;z-index:0;background:linear-gradient(180deg,var(--ra-wash1),transparent 34%,var(--ra-wash2));transition:background 1.05s ease}#app{isolation:isolate}#app>header,#app>#chat,#app>.composerWrap{position:relative;z-index:2}.brand b{color:var(--ra-accent)!important;transition:color .9s ease;text-shadow:0 0 18px var(--ra-soft)}.assistant .bubble{transition:border-color .9s ease,box-shadow .9s ease;border-color:var(--ra-border);box-shadow:0 8px 32px var(--ra-shadow)}.user .bubble{transition:background .9s ease,border-color .9s ease;background:linear-gradient(135deg,var(--ra-user1),var(--ra-user2));border-color:var(--ra-border)}.composer{transition:border-color .9s ease,box-shadow .9s ease;border-color:var(--ra-border);box-shadow:0 -5px 30px var(--ra-shadow)}.sendBtn{transition:background .9s ease,box-shadow .9s ease;background:linear-gradient(135deg,var(--ra-accent),var(--ra-send2));box-shadow:0 5px 20px var(--ra-shadow)}
#rAuraFX{position:fixed;inset:0;pointer-events:none;overflow:hidden;z-index:1;max-width:760px;margin:auto;opacity:var(--ra-fx-opacity);transition:opacity .8s ease}#rAuraFX i{position:absolute;display:block;font-style:normal;will-change:transform,opacity;user-select:none}.p-bubble{width:var(--z);height:var(--z);left:var(--x);bottom:-12%;border-radius:50%;border:1px solid var(--ra-particle);background:radial-gradient(circle at 34% 28%,rgba(255,255,255,.26),var(--ra-particle2) 48%,transparent 70%);animation:aFloat var(--d) linear var(--delay) infinite}.p-dot{left:var(--x);top:var(--y);font-size:var(--z);color:var(--ra-particle);text-shadow:0 0 11px var(--ra-particle2);animation:aPulse var(--d) ease-in-out var(--delay) infinite}.p-mist{width:var(--z);height:var(--z);left:var(--x);top:var(--y);border-radius:50%;background:var(--ra-particle2);filter:blur(1px);animation:aMist var(--d) ease-in-out var(--delay) infinite}.p-rain{width:2px;height:13px;left:var(--x);top:-8%;border-radius:99px;background:linear-gradient(transparent,var(--ra-particle));animation:aRain var(--d) linear var(--delay) infinite}.p-ember{left:var(--x);bottom:-8%;width:var(--z);height:var(--z);border-radius:50%;background:var(--ra-particle);box-shadow:0 0 10px var(--ra-particle2);animation:aEmber var(--d) ease-out var(--delay) infinite}@keyframes aFloat{0%{transform:translate3d(0,0,0) scale(.72);opacity:0}16%{opacity:.65}100%{transform:translate3d(var(--dx),-120vh,0) scale(1.15);opacity:0}}@keyframes aPulse{0%,100%{transform:scale(.55) rotate(0deg);opacity:.12}50%{transform:scale(1.15) rotate(32deg);opacity:.88}}@keyframes aMist{0%,100%{transform:translate3d(-8px,4px,0) scale(.75);opacity:.06}50%{transform:translate3d(12px,-9px,0) scale(1.26);opacity:.48}}@keyframes aRain{0%{transform:translateY(-10vh);opacity:0}16%{opacity:.6}100%{transform:translateY(116vh);opacity:0}}@keyframes aEmber{0%{transform:translate3d(0,0,0) scale(.45);opacity:0}14%{opacity:.8}100%{transform:translate3d(var(--dx),-108vh,0) scale(.15);opacity:0}}
body.r-peak-flash::after{content:"";position:fixed;inset:0;z-index:60;pointer-events:none;background:radial-gradient(circle at 50% 48%,rgba(255,248,252,.76),var(--ra-soft) 30%,var(--ra-soft2) 58%,transparent 76%);animation:rPeakFlash 2.65s ease-out both}body.r-peak-flash .assistant .bubble{animation:rBubblePulse 1.9s ease-out}@keyframes rPeakFlash{0%{opacity:0}10%{opacity:1}34%{opacity:.55}100%{opacity:0}}@keyframes rBubblePulse{0%,100%{transform:scale(1)}22%{transform:scale(1.012);box-shadow:0 0 38px var(--ra-particle)}55%{transform:scale(.998)}}#rPeakBurst{position:fixed;inset:0;max-width:760px;margin:auto;z-index:61;pointer-events:none;overflow:hidden}#rPeakBurst i{position:absolute;left:50%;top:48%;font-style:normal;color:var(--ra-particle);font-size:var(--z);text-shadow:0 0 15px var(--ra-particle2);animation:rPeakBurst 2.5s cubic-bezier(.16,.75,.24,1) var(--delay) both}@keyframes rPeakBurst{0%{transform:translate3d(0,0,0) scale(.25) rotate(0deg);opacity:0}12%{opacity:1}100%{transform:translate3d(var(--dx),var(--dy),0) scale(1.2) rotate(var(--rot));opacity:0}}@media (prefers-reduced-motion:reduce){#rAuraFX,#rPeakBurst{display:none!important}body.r-peak-flash::after{animation:none;opacity:.16}.assistant .bubble{animation:none!important}}
`;document.head.appendChild(s)}
  function layer(){let e=document.getElementById('rAuraFX');if(!e){e=document.createElement('div');e.id='rAuraFX';document.body.appendChild(e)}return e}
  function rand(a,b){return a+Math.random()*(b-a)}
  function speed(m){return m==='still'?1.8:m==='pulse'?.78:m==='float'?.9:m==='drift'?1.15:1.35}
  function ambient(a){const key=[a.particle,a.motion,a.intensity,a.hue,a.secondaryHue].join(':');if(key===ambientKey)return;ambientKey=key;const e=layer();e.textContent='';if(a.particle==='none'||a.intensity<=4)return;const n=Math.max(3,Math.round(4+a.intensity*.18)),sp=speed(a.motion);for(let i=0;i<n;i++){const p=document.createElement('i'),t=a.particle;if(t==='bubbles'){p.className='p-bubble';p.style.setProperty('--z',rand(7,25)+'px');p.style.setProperty('--x',rand(3,97)+'%');p.style.setProperty('--d',rand(8,15)*sp+'s');p.style.setProperty('--delay',-rand(0,12)+'s');p.style.setProperty('--dx',rand(-46,46)+'px')}else if(t==='mist'){p.className='p-mist';p.style.setProperty('--z',rand(16,46)+'px');p.style.setProperty('--x',rand(4,96)+'%');p.style.setProperty('--y',rand(8,92)+'%');p.style.setProperty('--d',rand(5,10)*sp+'s');p.style.setProperty('--delay',-rand(0,8)+'s')}else if(t==='rain'){p.className='p-rain';p.style.setProperty('--x',rand(3,97)+'%');p.style.setProperty('--d',rand(6,12)*sp+'s');p.style.setProperty('--delay',-rand(0,10)+'s')}else if(t==='embers'){p.className='p-ember';p.style.setProperty('--z',rand(2,6)+'px');p.style.setProperty('--x',rand(3,97)+'%');p.style.setProperty('--d',rand(6,11)*sp+'s');p.style.setProperty('--delay',-rand(0,8)+'s');p.style.setProperty('--dx',rand(-50,50)+'px')}else{p.className='p-dot';p.textContent=t==='hearts'?'♡':t==='stars'?(Math.random()<.55?'✦':'✧'):t==='sparks'?(Math.random()<.6?'✦':'·'):'·';p.style.setProperty('--z',rand(7,16)+'px');p.style.setProperty('--x',rand(4,96)+'%');p.style.setProperty('--y',rand(8,90)+'%');p.style.setProperty('--d',rand(2.8,5.8)*sp+'s');p.style.setProperty('--delay',-rand(0,5)+'s')}e.appendChild(p)}}
  function apply(raw){const a=norm(raw);if(!a)return;current=a;const q=a.intensity/100,r=document.documentElement;r.style.setProperty('--ra-accent',hsl(a.hue,a.saturation,a.lightness));r.style.setProperty('--ra-soft',hsl(a.hue,a.saturation,a.lightness,0.04+q*.25));r.style.setProperty('--ra-soft2',hsl(a.secondaryHue,Math.max(24,a.saturation-8),Math.max(34,a.lightness-7),0.025+q*.20));r.style.setProperty('--ra-border',hsl(a.hue,a.saturation,Math.min(78,a.lightness+8),0.16+q*.36));r.style.setProperty('--ra-shadow',hsl(a.hue,a.saturation,45,0.02+q*.12));r.style.setProperty('--ra-user1',hsl(a.hue,Math.max(34,a.saturation-16),Math.max(18,a.lightness-32)));r.style.setProperty('--ra-user2',hsl(a.secondaryHue,Math.max(28,a.saturation-26),Math.max(11,a.lightness-42)));r.style.setProperty('--ra-send2',hsl(a.secondaryHue,Math.max(38,a.saturation-15),Math.max(24,a.lightness-26)));r.style.setProperty('--ra-wash1',hsl(a.hue,a.saturation,20,0.015+q*.11));r.style.setProperty('--ra-wash2',hsl(a.secondaryHue,Math.max(30,a.saturation-15),18,0.01+q*.08));r.style.setProperty('--ra-particle',hsl(a.hue,Math.min(96,a.saturation+8),Math.min(88,a.lightness+18),0.28+q*.58));r.style.setProperty('--ra-particle2',hsl(a.secondaryHue,Math.min(92,a.saturation+2),Math.min(82,a.lightness+10),0.12+q*.32));r.style.setProperty('--ra-fx-opacity',(0.16+q*.84).toFixed(2));ambient(a);const m=document.querySelector('meta[name="theme-color"]');if(m)m.setAttribute('content',hsl(a.hue,Math.max(18,a.saturation-20),8))}
  function peak(evt){if(!evt?.id)return;const seen=localStorage.getItem(K.peakSeen)||'';if(seen===String(evt.id))return;localStorage.setItem(K.peakSeen,String(evt.id));document.body.classList.remove('r-peak-flash');void document.body.offsetWidth;document.body.classList.add('r-peak-flash');document.getElementById('rPeakBurst')?.remove();const b=document.createElement('div');b.id='rPeakBurst';document.body.appendChild(b);const n=evt.variant==='secret'?36:evt.variant==='petals'?28:31;for(let i=0;i<n;i++){const p=document.createElement('i'),ang=rand(0,Math.PI*2),dist=rand(85,330);p.textContent=evt.variant==='petals'?(Math.random()<.65?'❀':'·'):(evt.variant==='secret'?(Math.random()<.26?'♡':'✦'):(Math.random()<.38?'♡':'●'));p.style.setProperty('--dx',Math.cos(ang)*dist+'px');p.style.setProperty('--dy',Math.sin(ang)*dist+'px');p.style.setProperty('--rot',rand(-220,220)+'deg');p.style.setProperty('--z',rand(8,20)+'px');p.style.setProperty('--delay',rand(0,.18)+'s');b.appendChild(p)}setTimeout(()=>document.body.classList.remove('r-peak-flash'),2800);setTimeout(()=>b.remove(),3100)}
  function consume(s){if(!s||typeof s!=='object')return;if(s.auraState)apply(s.auraState);if(s.peakEvent)peak(s.peakEvent)}
  installCSS();const a=safe(localStorage.getItem(K.aura),null),p=safe(localStorage.getItem(K.peak),null);apply(a||legacy({mode:'calm'}));if(p)peak(p);window.addEventListener('red:server-state',e=>consume(e.detail));window.REDAura={version:V,apply,consume,current:()=>current,peak};
})();